NUTRITION_LOOKUP = {
    "almond": {
        "density": 0.6,
        "cal_100g": 579.0,
        "protein": 21.2,
        "fat": 49.9,
        "carbs": 21.7,
        "sugars": 4.4,
        "cholesterol": 0.0,
        "dietary_fiber": 12.5,
        "nutrition_density": 88.0,
        "ingredients": ["raw almonds"]
    },
    "apple": {
        "density": 0.55,
        "cal_100g": 52.0,
        "protein": 0.3,
        "fat": 0.2,
        "carbs": 13.8,
        "sugars": 10.4,
        "cholesterol": 0.0,
        "dietary_fiber": 2.4,
        "nutrition_density": 75.0,
        "ingredients": ["fresh apple"]
    },
    "apricot": {
        "density": 0.6,
        "cal_100g": 48.0,
        "protein": 1.4,
        "fat": 0.4,
        "carbs": 11.1,
        "sugars": 9.2,
        "cholesterol": 0.0,
        "dietary_fiber": 2.0,
        "nutrition_density": 78.0,
        "ingredients": ["fresh apricot"]
    },
    "asparagus": {
        "density": 0.4,
        "cal_100g": 20.0,
        "protein": 2.2,
        "fat": 0.1,
        "carbs": 3.9,
        "sugars": 1.9,
        "cholesterol": 0.0,
        "dietary_fiber": 2.1,
        "nutrition_density": 90.0,
        "ingredients": ["cooked asparagus"]
    },
    "avocado": {
        "density": 0.9,
        "cal_100g": 160.0,
        "protein": 2.0,
        "fat": 14.7,
        "carbs": 8.5,
        "sugars": 0.7,
        "cholesterol": 0.0,
        "dietary_fiber": 6.7,
        "nutrition_density": 92.0,
        "ingredients": ["fresh avocado"]
    },
    "bamboo shoots": {
        "density": 0.5,
        "cal_100g": 27.0,
        "protein": 2.6,
        "fat": 0.3,
        "carbs": 5.2,
        "sugars": 3.0,
        "cholesterol": 0.0,
        "dietary_fiber": 2.2,
        "nutrition_density": 70.0,
        "ingredients": ["bamboo shoots"]
    },
    "banana": {
        "density": 0.65,
        "cal_100g": 89.0,
        "protein": 1.1,
        "fat": 0.3,
        "carbs": 22.8,
        "sugars": 12.2,
        "cholesterol": 0.0,
        "dietary_fiber": 2.6,
        "nutrition_density": 80.0,
        "ingredients": ["fresh banana"]
    },
    "bean sprouts": {
        "density": 0.3,
        "cal_100g": 30.0,
        "protein": 3.0,
        "fat": 0.2,
        "carbs": 5.9,
        "sugars": 4.1,
        "cholesterol": 0.0,
        "dietary_fiber": 1.8,
        "nutrition_density": 82.0,
        "ingredients": ["mung bean sprouts"]
    },
    "biscuit": {
        "density": 0.7,
        "cal_100g": 353.0,
        "protein": 7.0,
        "fat": 16.0,
        "carbs": 45.0,
        "sugars": 2.0,
        "cholesterol": 2.0,
        "dietary_fiber": 2.3,
        "nutrition_density": 40.0,
        "ingredients": ["wheat flour", "butter", "sugar", "baking powder"]
    },
    "blueberry": {
        "density": 0.6,
        "cal_100g": 57.0,
        "protein": 0.7,
        "fat": 0.3,
        "carbs": 14.5,
        "sugars": 9.9,
        "cholesterol": 0.0,
        "dietary_fiber": 2.4,
        "nutrition_density": 94.0,
        "ingredients": ["fresh blueberries"]
    },
    "bread": {
        "density": 0.35,
        "cal_100g": 265.0,
        "protein": 9.0,
        "fat": 3.2,
        "carbs": 49.0,
        "sugars": 5.0,
        "cholesterol": 0.0,
        "dietary_fiber": 2.7,
        "nutrition_density": 60.0,
        "ingredients": ["wheat flour", "water", "yeast", "salt"]
    },
    "broccoli": {
        "density": 0.38,
        "cal_100g": 34.0,
        "protein": 2.8,
        "fat": 0.4,
        "carbs": 6.6,
        "sugars": 1.7,
        "cholesterol": 0.0,
        "dietary_fiber": 2.6,
        "nutrition_density": 95.0,
        "ingredients": ["fresh broccoli"]
    },
    "cabbage": {
        "density": 0.35,
        "cal_100g": 25.0,
        "protein": 1.3,
        "fat": 0.1,
        "carbs": 5.8,
        "sugars": 3.2,
        "cholesterol": 0.0,
        "dietary_fiber": 2.5,
        "nutrition_density": 85.0,
        "ingredients": ["green cabbage"]
    },
    "cake": {
        "density": 0.5,
        "cal_100g": 371.0,
        "protein": 5.3,
        "fat": 15.1,
        "carbs": 53.4,
        "sugars": 35.0,
        "cholesterol": 58.0,
        "dietary_fiber": 0.8,
        "nutrition_density": 25.0,
        "ingredients": ["flour", "sugar", "eggs", "butter", "baking powder"]
    },
    "candy": {
        "density": 0.8,
        "cal_100g": 394.0,
        "protein": 0.0,
        "fat": 0.2,
        "carbs": 98.0,
        "sugars": 62.9,
        "cholesterol": 0.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 10.0,
        "ingredients": ["sugar", "corn syrup", "flavoring", "colorings"]
    },
    "carrot": {
        "density": 0.64,
        "cal_100g": 41.0,
        "protein": 0.9,
        "fat": 0.2,
        "carbs": 9.6,
        "sugars": 4.7,
        "cholesterol": 0.0,
        "dietary_fiber": 2.8,
        "nutrition_density": 88.0,
        "ingredients": ["fresh carrot"]
    },
    "cashew": {
        "density": 0.6,
        "cal_100g": 553.0,
        "protein": 18.2,
        "fat": 43.8,
        "carbs": 30.2,
        "sugars": 5.9,
        "cholesterol": 0.0,
        "dietary_fiber": 3.3,
        "nutrition_density": 82.0,
        "ingredients": ["raw cashews"]
    },
    "cauliflower": {
        "density": 0.35,
        "cal_100g": 25.0,
        "protein": 1.9,
        "fat": 0.3,
        "carbs": 5.0,
        "sugars": 1.9,
        "cholesterol": 0.0,
        "dietary_fiber": 2.0,
        "nutrition_density": 89.0,
        "ingredients": ["fresh cauliflower"]
    },
    "celery stick": {
        "density": 0.4,
        "cal_100g": 14.0,
        "protein": 0.7,
        "fat": 0.2,
        "carbs": 3.0,
        "sugars": 1.3,
        "cholesterol": 0.0,
        "dietary_fiber": 1.6,
        "nutrition_density": 86.0,
        "ingredients": ["fresh celery"]
    },
    "cheese butter": {
        "density": 0.9,
        "cal_100g": 717.0,
        "protein": 0.9,
        "fat": 81.0,
        "carbs": 0.1,
        "sugars": 0.1,
        "cholesterol": 215.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 30.0,
        "ingredients": ["pasteurized cream", "salt", "milk solids"]
    },
    "cherry": {
        "density": 0.65,
        "cal_100g": 63.0,
        "protein": 1.1,
        "fat": 0.2,
        "carbs": 16.0,
        "sugars": 12.8,
        "cholesterol": 0.0,
        "dietary_fiber": 2.1,
        "nutrition_density": 81.0,
        "ingredients": ["fresh cherries"]
    },
    "chicken duck": {
        "density": 0.85,
        "cal_100g": 239.0,
        "protein": 27.0,
        "fat": 14.0,
        "carbs": 0.0,
        "sugars": 0.0,
        "cholesterol": 88.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 85.0,
        "ingredients": ["roasted poultry meat", "seasoning"]
    },
    "chocolate": {
        "density": 0.75,
        "cal_100g": 546.0,
        "protein": 4.9,
        "fat": 31.0,
        "carbs": 61.0,
        "sugars": 48.0,
        "cholesterol": 8.0,
        "dietary_fiber": 7.0,
        "nutrition_density": 45.0,
        "ingredients": ["cocoa mass", "cocoa butter", "sugar", "milk powder"]
    },
    "cilantro mint": {
        "density": 0.2,
        "cal_100g": 23.0,
        "protein": 2.1,
        "fat": 0.5,
        "carbs": 3.7,
        "sugars": 0.9,
        "cholesterol": 0.0,
        "dietary_fiber": 2.8,
        "nutrition_density": 95.0,
        "ingredients": ["fresh cilantro", "fresh mint leaves"]
    },
    "coffee": {
        "density": 1.0,
        "cal_100g": 1.0,
        "protein": 0.1,
        "fat": 0.0,
        "carbs": 0.0,
        "sugars": 0.0,
        "cholesterol": 0.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 65.0,
        "ingredients": ["brewed coffee", "water"]
    },
    "corn": {
        "density": 0.7,
        "cal_100g": 86.0,
        "protein": 3.2,
        "fat": 1.2,
        "carbs": 19.0,
        "sugars": 3.2,
        "cholesterol": 0.0,
        "dietary_fiber": 2.7,
        "nutrition_density": 83.0,
        "ingredients": ["sweet corn kernels"]
    },
    "crab": {
        "density": 0.85,
        "cal_100g": 97.0,
        "protein": 19.0,
        "fat": 1.5,
        "carbs": 0.0,
        "sugars": 0.0,
        "cholesterol": 78.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 90.0,
        "ingredients": ["steamed crab meat"]
    },
    "cucumber": {
        "density": 0.6,
        "cal_100g": 15.0,
        "protein": 0.7,
        "fat": 0.1,
        "carbs": 3.6,
        "sugars": 1.7,
        "cholesterol": 0.0,
        "dietary_fiber": 0.5,
        "nutrition_density": 80.0,
        "ingredients": ["fresh cucumber"]
    },
    "date": {
        "density": 0.8,
        "cal_100g": 277.0,
        "protein": 1.8,
        "fat": 0.2,
        "carbs": 75.0,
        "sugars": 66.0,
        "cholesterol": 0.0,
        "dietary_fiber": 6.7,
        "nutrition_density": 70.0,
        "ingredients": ["dried dates"]
    },
    "dried cranberries": {
        "density": 0.7,
        "cal_100g": 308.0,
        "protein": 0.1,
        "fat": 1.1,
        "carbs": 82.0,
        "sugars": 65.0,
        "cholesterol": 0.0,
        "dietary_fiber": 5.3,
        "nutrition_density": 60.0,
        "ingredients": ["cranberries", "sugar", "sunflower oil"]
    },
    "egg": {
        "density": 0.6,
        "cal_100g": 155.0,
        "protein": 12.6,
        "fat": 10.6,
        "carbs": 1.1,
        "sugars": 1.1,
        "cholesterol": 373.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 88.0,
        "ingredients": ["whole chicken egg"]
    },
    "egg tart": {
        "density": 0.7,
        "cal_100g": 298.0,
        "protein": 5.8,
        "fat": 18.2,
        "carbs": 27.5,
        "sugars": 14.1,
        "cholesterol": 112.0,
        "dietary_fiber": 0.8,
        "nutrition_density": 42.0,
        "ingredients": ["egg custard", "pastry flour", "butter", "sugar"]
    },
    "eggplant": {
        "density": 0.4,
        "cal_100g": 25.0,
        "protein": 1.0,
        "fat": 0.2,
        "carbs": 5.9,
        "sugars": 3.5,
        "cholesterol": 0.0,
        "dietary_fiber": 3.0,
        "nutrition_density": 84.0,
        "ingredients": ["cooked eggplant"]
    },
    "enoki mushroom": {
        "density": 0.3,
        "cal_100g": 37.0,
        "protein": 2.7,
        "fat": 0.3,
        "carbs": 7.8,
        "sugars": 0.2,
        "cholesterol": 0.0,
        "dietary_fiber": 2.7,
        "nutrition_density": 89.0,
        "ingredients": ["fresh enoki mushrooms"]
    },
    "fig": {
        "density": 0.7,
        "cal_100g": 74.0,
        "protein": 0.8,
        "fat": 0.3,
        "carbs": 19.2,
        "sugars": 16.3,
        "cholesterol": 0.0,
        "dietary_fiber": 2.9,
        "nutrition_density": 82.0,
        "ingredients": ["fresh figs"]
    },
    "fish": {
        "density": 0.85,
        "cal_100g": 206.0,
        "protein": 22.0,
        "fat": 12.0,
        "carbs": 0.0,
        "sugars": 0.0,
        "cholesterol": 63.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 92.0,
        "ingredients": ["steamed fish fillet"]
    },
    "french beans": {
        "density": 0.4,
        "cal_100g": 31.0,
        "protein": 1.8,
        "fat": 0.1,
        "carbs": 7.0,
        "sugars": 3.3,
        "cholesterol": 0.0,
        "dietary_fiber": 3.4,
        "nutrition_density": 87.0,
        "ingredients": ["green french beans"]
    },
    "french fries": {
        "density": 0.5,
        "cal_100g": 312.0,
        "protein": 3.4,
        "fat": 15.0,
        "carbs": 41.0,
        "sugars": 0.3,
        "cholesterol": 0.0,
        "dietary_fiber": 3.8,
        "nutrition_density": 35.0,
        "ingredients": ["potatoes", "vegetable oil", "salt"]
    },
    "fried meat": {
        "density": 0.8,
        "cal_100g": 280.0,
        "protein": 24.0,
        "fat": 20.0,
        "carbs": 2.0,
        "sugars": 0.0,
        "cholesterol": 85.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 65.0,
        "ingredients": ["fried meat cuts", "cooking oil", "salt", "spices"]
    },
    "garlic": {
        "density": 0.6,
        "cal_100g": 149.0,
        "protein": 6.4,
        "fat": 0.5,
        "carbs": 33.0,
        "sugars": 1.0,
        "cholesterol": 0.0,
        "dietary_fiber": 2.1,
        "nutrition_density": 90.0,
        "ingredients": ["fresh garlic cloves"]
    },
    "ginger": {
        "density": 0.5,
        "cal_100g": 80.0,
        "protein": 1.8,
        "fat": 0.8,
        "carbs": 17.8,
        "sugars": 1.7,
        "cholesterol": 0.0,
        "dietary_fiber": 2.0,
        "nutrition_density": 91.0,
        "ingredients": ["fresh ginger root"]
    },
    "grape": {
        "density": 0.65,
        "cal_100g": 69.0,
        "protein": 0.7,
        "fat": 0.2,
        "carbs": 18.1,
        "sugars": 15.5,
        "cholesterol": 0.0,
        "dietary_fiber": 0.9,
        "nutrition_density": 77.0,
        "ingredients": ["fresh grapes"]
    },
    "green beans": {
        "density": 0.4,
        "cal_100g": 31.0,
        "protein": 1.8,
        "fat": 0.2,
        "carbs": 7.0,
        "sugars": 3.3,
        "cholesterol": 0.0,
        "dietary_fiber": 2.7,
        "nutrition_density": 86.0,
        "ingredients": ["cooked green beans"]
    },
    "hamburg": {
        "density": 0.8,
        "cal_100g": 254.0,
        "protein": 17.0,
        "fat": 15.0,
        "carbs": 12.0,
        "sugars": 2.0,
        "cholesterol": 47.0,
        "dietary_fiber": 1.0,
        "nutrition_density": 60.0,
        "ingredients": ["beef patty", "bun", "lettuce", "sauce"]
    },
    "hanamaki baozi": {
        "density": 0.5,
        "cal_100g": 220.0,
        "protein": 6.5,
        "fat": 2.1,
        "carbs": 44.0,
        "sugars": 3.5,
        "cholesterol": 0.0,
        "dietary_fiber": 1.5,
        "nutrition_density": 58.0,
        "ingredients": ["wheat flour", "yeast", "scallion oil", "salt"]
    },
    "ice cream": {
        "density": 0.6,
        "cal_100g": 207.0,
        "protein": 3.5,
        "fat": 11.0,
        "carbs": 24.0,
        "sugars": 21.0,
        "cholesterol": 44.0,
        "dietary_fiber": 0.7,
        "nutrition_density": 35.0,
        "ingredients": ["milk", "cream", "sugar", "vanilla extract"]
    },
    "juice": {
        "density": 1.0,
        "cal_100g": 45.0,
        "protein": 0.5,
        "fat": 0.2,
        "carbs": 10.4,
        "sugars": 8.4,
        "cholesterol": 0.0,
        "dietary_fiber": 0.2,
        "nutrition_density": 68.0,
        "ingredients": ["fruit juice extract", "water"]
    },
    "kelp": {
        "density": 0.4,
        "cal_100g": 43.0,
        "protein": 1.7,
        "fat": 0.6,
        "carbs": 9.6,
        "sugars": 0.6,
        "cholesterol": 0.0,
        "dietary_fiber": 1.3,
        "nutrition_density": 93.0,
        "ingredients": ["edible kelp seaweed"]
    },
    "king oyster mushroom": {
        "density": 0.4,
        "cal_100g": 35.0,
        "protein": 2.5,
        "fat": 0.5,
        "carbs": 6.5,
        "sugars": 1.0,
        "cholesterol": 0.0,
        "dietary_fiber": 2.3,
        "nutrition_density": 90.0,
        "ingredients": ["king oyster mushroom"]
    },
    "kiwi": {
        "density": 0.65,
        "cal_100g": 61.0,
        "protein": 1.1,
        "fat": 0.5,
        "carbs": 14.7,
        "sugars": 9.0,
        "cholesterol": 0.0,
        "dietary_fiber": 3.0,
        "nutrition_density": 89.0,
        "ingredients": ["fresh kiwi fruit"]
    },
    "lamb": {
        "density": 0.85,
        "cal_100g": 294.0,
        "protein": 25.0,
        "fat": 21.0,
        "carbs": 0.0,
        "sugars": 0.0,
        "cholesterol": 97.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 80.0,
        "ingredients": ["cooked lamb meat"]
    },
    "lemon": {
        "density": 0.6,
        "cal_100g": 29.0,
        "protein": 1.1,
        "fat": 0.3,
        "carbs": 9.3,
        "sugars": 2.5,
        "cholesterol": 0.0,
        "dietary_fiber": 2.8,
        "nutrition_density": 91.0,
        "ingredients": ["fresh lemon"]
    },
    "lettuce": {
        "density": 0.25,
        "cal_100g": 15.0,
        "protein": 1.4,
        "fat": 0.2,
        "carbs": 2.9,
        "sugars": 0.8,
        "cholesterol": 0.0,
        "dietary_fiber": 1.3,
        "nutrition_density": 88.0,
        "ingredients": ["fresh lettuce leaves"]
    },
    "mango": {
        "density": 0.65,
        "cal_100g": 60.0,
        "protein": 0.8,
        "fat": 0.4,
        "carbs": 15.0,
        "sugars": 13.7,
        "cholesterol": 0.0,
        "dietary_fiber": 1.6,
        "nutrition_density": 82.0,
        "ingredients": ["fresh mango"]
    },
    "melon": {
        "density": 0.6,
        "cal_100g": 34.0,
        "protein": 0.8,
        "fat": 0.2,
        "carbs": 8.2,
        "sugars": 7.9,
        "cholesterol": 0.0,
        "dietary_fiber": 0.9,
        "nutrition_density": 80.0,
        "ingredients": ["fresh melon"]
    },
    "milk": {
        "density": 1.03,
        "cal_100g": 42.0,
        "protein": 3.4,
        "fat": 1.0,
        "carbs": 5.0,
        "sugars": 5.0,
        "cholesterol": 5.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 85.0,
        "ingredients": ["pasteurized cow milk"]
    },
    "milkshake": {
        "density": 0.9,
        "cal_100g": 112.0,
        "protein": 3.0,
        "fat": 3.0,
        "carbs": 18.0,
        "sugars": 17.0,
        "cholesterol": 12.0,
        "dietary_fiber": 0.4,
        "nutrition_density": 45.0,
        "ingredients": ["milk", "ice cream", "flavoring syrup"]
    },
    "noodles": {
        "density": 0.85,
        "cal_100g": 211.0,
        "protein": 8.1,
        "fat": 2.5,
        "carbs": 38.8,
        "sugars": 1.1,
        "cholesterol": 52.8,
        "dietary_fiber": 3.7,
        "nutrition_density": 85.3,
        "ingredients": ["spinach egg noodles cooked"]
    },
    "okra": {
        "density": 0.45,
        "cal_100g": 33.0,
        "protein": 1.9,
        "fat": 0.2,
        "carbs": 7.5,
        "sugars": 1.5,
        "cholesterol": 0.0,
        "dietary_fiber": 3.2,
        "nutrition_density": 91.0,
        "ingredients": ["cooked okra"]
    },
    "olives": {
        "density": 0.7,
        "cal_100g": 115.0,
        "protein": 0.8,
        "fat": 10.7,
        "carbs": 6.3,
        "sugars": 0.0,
        "cholesterol": 0.0,
        "dietary_fiber": 3.2,
        "nutrition_density": 78.0,
        "ingredients": ["cured olives", "brine"]
    },
    "onion": {
        "density": 0.55,
        "cal_100g": 40.0,
        "protein": 1.1,
        "fat": 0.1,
        "carbs": 9.3,
        "sugars": 4.2,
        "cholesterol": 0.0,
        "dietary_fiber": 1.7,
        "nutrition_density": 82.0,
        "ingredients": ["fresh yellow onion"]
    },
    "orange": {
        "density": 0.6,
        "cal_100g": 47.0,
        "protein": 0.9,
        "fat": 0.1,
        "carbs": 11.8,
        "sugars": 9.4,
        "cholesterol": 0.0,
        "dietary_fiber": 2.4,
        "nutrition_density": 87.0,
        "ingredients": ["fresh orange"]
    },
    "other ingredients": {
        "density": 0.5,
        "cal_100g": 100.0,
        "protein": 3.0,
        "fat": 2.0,
        "carbs": 15.0,
        "sugars": 2.0,
        "cholesterol": 0.0,
        "dietary_fiber": 1.0,
        "nutrition_density": 50.0,
        "ingredients": ["assorted food items"]
    },
    "oyster mushroom": {
        "density": 0.35,
        "cal_100g": 33.0,
        "protein": 3.3,
        "fat": 0.4,
        "carbs": 6.1,
        "sugars": 1.1,
        "cholesterol": 0.0,
        "dietary_fiber": 2.3,
        "nutrition_density": 91.0,
        "ingredients": ["fresh oyster mushroom"]
    },
    "pasta": {
        "density": 0.7,
        "cal_100g": 131.0,
        "protein": 5.0,
        "fat": 1.1,
        "carbs": 25.0,
        "sugars": 0.6,
        "cholesterol": 0.0,
        "dietary_fiber": 1.8,
        "nutrition_density": 72.0,
        "ingredients": ["durum wheat semolina pasta"]
    },
    "peach": {
        "density": 0.6,
        "cal_100g": 39.0,
        "protein": 0.9,
        "fat": 0.3,
        "carbs": 9.5,
        "sugars": 8.4,
        "cholesterol": 0.0,
        "dietary_fiber": 1.5,
        "nutrition_density": 80.0,
        "ingredients": ["fresh peach"]
    },
    "peanut": {
        "density": 0.6,
        "cal_100g": 567.0,
        "protein": 25.8,
        "fat": 49.2,
        "carbs": 16.1,
        "sugars": 4.7,
        "cholesterol": 0.0,
        "dietary_fiber": 8.5,
        "nutrition_density": 84.0,
        "ingredients": ["roasted peanuts"]
    },
    "pear": {
        "density": 0.6,
        "cal_100g": 57.0,
        "protein": 0.4,
        "fat": 0.1,
        "carbs": 15.0,
        "sugars": 9.8,
        "cholesterol": 0.0,
        "dietary_fiber": 3.1,
        "nutrition_density": 78.0,
        "ingredients": ["fresh pear"]
    },
    "pepper": {
        "density": 0.4,
        "cal_100g": 20.0,
        "protein": 0.9,
        "fat": 0.2,
        "carbs": 4.6,
        "sugars": 2.4,
        "cholesterol": 0.0,
        "dietary_fiber": 1.7,
        "nutrition_density": 92.0,
        "ingredients": ["bell pepper"]
    },
    "pie": {
        "density": 0.6,
        "cal_100g": 237.0,
        "protein": 2.4,
        "fat": 11.0,
        "carbs": 34.0,
        "sugars": 15.0,
        "cholesterol": 0.0,
        "dietary_fiber": 1.4,
        "nutrition_density": 38.0,
        "ingredients": ["pastry dough", "fruit filling", "sugar"]
    },
    "pineapple": {
        "density": 0.6,
        "cal_100g": 50.0,
        "protein": 0.5,
        "fat": 0.1,
        "carbs": 13.1,
        "sugars": 9.9,
        "cholesterol": 0.0,
        "dietary_fiber": 1.4,
        "nutrition_density": 83.0,
        "ingredients": ["fresh pineapple"]
    },
    "pizza": {
        "density": 0.6,
        "cal_100g": 266.0,
        "protein": 11.0,
        "fat": 10.0,
        "carbs": 33.0,
        "sugars": 3.6,
        "cholesterol": 17.0,
        "dietary_fiber": 2.3,
        "nutrition_density": 55.0,
        "ingredients": ["wheat crust", "tomato sauce", "mozzarella cheese", "toppings"]
    },
    "popcorn": {
        "density": 0.1,
        "cal_100g": 387.0,
        "protein": 12.9,
        "fat": 4.5,
        "carbs": 77.9,
        "sugars": 0.9,
        "cholesterol": 0.0,
        "dietary_fiber": 14.5,
        "nutrition_density": 65.0,
        "ingredients": ["popped corn kernels", "salt"]
    },
    "pork": {
        "density": 0.85,
        "cal_100g": 242.0,
        "protein": 27.0,
        "fat": 14.0,
        "carbs": 0.0,
        "sugars": 0.0,
        "cholesterol": 80.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 82.0,
        "ingredients": ["cooked pork meat"]
    },
    "potato": {
        "density": 0.65,
        "cal_100g": 77.0,
        "protein": 2.0,
        "fat": 0.1,
        "carbs": 17.0,
        "sugars": 0.8,
        "cholesterol": 0.0,
        "dietary_fiber": 2.2,
        "nutrition_density": 76.0,
        "ingredients": ["boiled potato"]
    },
    "pudding": {
        "density": 0.8,
        "cal_100g": 130.0,
        "protein": 3.0,
        "fat": 3.0,
        "carbs": 22.0,
        "sugars": 17.0,
        "cholesterol": 10.0,
        "dietary_fiber": 0.5,
        "nutrition_density": 40.0,
        "ingredients": ["milk", "sugar", "cornstarch", "flavoring"]
    },
    "pumpkin": {
        "density": 0.5,
        "cal_100g": 26.0,
        "protein": 1.0,
        "fat": 0.1,
        "carbs": 6.5,
        "sugars": 2.8,
        "cholesterol": 0.0,
        "dietary_fiber": 0.5,
        "nutrition_density": 87.0,
        "ingredients": ["cooked pumpkin"]
    },
    "rape": {
        "density": 0.3,
        "cal_100g": 22.0,
        "protein": 2.0,
        "fat": 0.4,
        "carbs": 4.0,
        "sugars": 1.0,
        "cholesterol": 0.0,
        "dietary_fiber": 2.0,
        "nutrition_density": 92.0,
        "ingredients": ["rapeseed greens / oilseed rape"]
    },
    "raspberry": {
        "density": 0.6,
        "cal_100g": 52.0,
        "protein": 1.2,
        "fat": 0.7,
        "carbs": 11.9,
        "sugars": 4.4,
        "cholesterol": 0.0,
        "dietary_fiber": 6.5,
        "nutrition_density": 95.0,
        "ingredients": ["fresh raspberries"]
    },
    "red beans": {
        "density": 0.7,
        "cal_100g": 127.0,
        "protein": 8.7,
        "fat": 0.5,
        "carbs": 22.8,
        "sugars": 0.3,
        "cholesterol": 0.0,
        "dietary_fiber": 6.4,
        "nutrition_density": 88.0,
        "ingredients": ["cooked red kidney beans"]
    },
    "rice": {
        "density": 0.85,
        "cal_100g": 130.0,
        "protein": 2.7,
        "fat": 0.3,
        "carbs": 28.0,
        "sugars": 0.1,
        "cholesterol": 0.0,
        "dietary_fiber": 0.4,
        "nutrition_density": 70.0,
        "ingredients": ["cooked white rice"]
    },
    "salad": {
        "density": 0.3,
        "cal_100g": 45.0,
        "protein": 1.5,
        "fat": 2.5,
        "carbs": 4.5,
        "sugars": 2.0,
        "cholesterol": 0.0,
        "dietary_fiber": 2.0,
        "nutrition_density": 88.0,
        "ingredients": ["mixed leafy greens", "dressing"]
    },
    "sauce": {
        "density": 1.0,
        "cal_100g": 80.0,
        "protein": 1.2,
        "fat": 4.0,
        "carbs": 10.0,
        "sugars": 6.0,
        "cholesterol": 2.0,
        "dietary_fiber": 0.8,
        "nutrition_density": 50.0,
        "ingredients": ["tomato paste", "oil", "spices", "sugar"]
    },
    "sausage": {
        "density": 0.8,
        "cal_100g": 301.0,
        "protein": 12.0,
        "fat": 27.0,
        "carbs": 2.0,
        "sugars": 1.0,
        "cholesterol": 70.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 52.0,
        "ingredients": ["minced meat", "spices", "casing"]
    },
    "seaweed": {
        "density": 0.3,
        "cal_100g": 45.0,
        "protein": 3.0,
        "fat": 0.6,
        "carbs": 9.1,
        "sugars": 0.5,
        "cholesterol": 0.0,
        "dietary_fiber": 0.3,
        "nutrition_density": 94.0,
        "ingredients": ["dried seaweed sheets"]
    },
    "shellfish": {
        "density": 0.85,
        "cal_100g": 90.0,
        "protein": 16.0,
        "fat": 1.0,
        "carbs": 3.0,
        "sugars": 0.0,
        "cholesterol": 50.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 92.0,
        "ingredients": ["steamed mixed shellfish"]
    },
    "shiitake": {
        "density": 0.35,
        "cal_100g": 34.0,
        "protein": 2.2,
        "fat": 0.5,
        "carbs": 6.8,
        "sugars": 2.4,
        "cholesterol": 0.0,
        "dietary_fiber": 2.5,
        "nutrition_density": 91.0,
        "ingredients": ["shiitake mushroom"]
    },
    "shrimp": {
        "density": 0.85,
        "cal_100g": 99.0,
        "protein": 24.0,
        "fat": 0.3,
        "carbs": 0.2,
        "sugars": 0.0,
        "cholesterol": 189.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 90.0,
        "ingredients": ["cooked shrimp"]
    },
    "snow peas": {
        "density": 0.35,
        "cal_100g": 42.0,
        "protein": 2.8,
        "fat": 0.2,
        "carbs": 7.5,
        "sugars": 4.0,
        "cholesterol": 0.0,
        "dietary_fiber": 2.6,
        "nutrition_density": 89.0,
        "ingredients": ["fresh snow peas"]
    },
    "soup": {
        "density": 0.95,
        "cal_100g": 36.0,
        "protein": 2.0,
        "fat": 1.2,
        "carbs": 4.5,
        "sugars": 1.2,
        "cholesterol": 3.0,
        "dietary_fiber": 0.8,
        "nutrition_density": 75.0,
        "ingredients": ["broth", "vegetables", "seasoning"]
    },
    "soy": {
        "density": 0.7,
        "cal_100g": 173.0,
        "protein": 16.6,
        "fat": 9.0,
        "carbs": 9.9,
        "sugars": 3.0,
        "cholesterol": 0.0,
        "dietary_fiber": 6.0,
        "nutrition_density": 88.0,
        "ingredients": ["cooked soybeans"]
    },
    "spring onion": {
        "density": 0.3,
        "cal_100g": 32.0,
        "protein": 1.8,
        "fat": 0.2,
        "carbs": 7.3,
        "sugars": 2.3,
        "cholesterol": 0.0,
        "dietary_fiber": 2.6,
        "nutrition_density": 90.0,
        "ingredients": ["fresh green spring onion"]
    },
    "steak": {
        "density": 0.85,
        "cal_100g": 271.0,
        "protein": 26.0,
        "fat": 18.0,
        "carbs": 0.0,
        "sugars": 0.0,
        "cholesterol": 78.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 84.0,
        "ingredients": ["grilled beef steak"]
    },
    "strawberry": {
        "density": 0.6,
        "cal_100g": 32.0,
        "protein": 0.7,
        "fat": 0.3,
        "carbs": 7.7,
        "sugars": 4.9,
        "cholesterol": 0.0,
        "dietary_fiber": 2.0,
        "nutrition_density": 92.0,
        "ingredients": ["fresh strawberries"]
    },
    "tea": {
        "density": 1.0,
        "cal_100g": 1.0,
        "protein": 0.0,
        "fat": 0.0,
        "carbs": 0.2,
        "sugars": 0.0,
        "cholesterol": 0.0,
        "dietary_fiber": 0.0,
        "nutrition_density": 70.0,
        "ingredients": ["brewed tea leaves", "water"]
    },
    "tofu": {
        "density": 0.8,
        "cal_100g": 76.0,
        "protein": 8.0,
        "fat": 4.8,
        "carbs": 1.9,
        "sugars": 0.6,
        "cholesterol": 0.0,
        "dietary_fiber": 0.3,
        "nutrition_density": 86.0,
        "ingredients": ["soybeans", "water", "coagulant"]
    },
    "tomato": {
        "density": 0.6,
        "cal_100g": 18.0,
        "protein": 0.9,
        "fat": 0.2,
        "carbs": 3.9,
        "sugars": 2.6,
        "cholesterol": 0.0,
        "dietary_fiber": 1.2,
        "nutrition_density": 89.0,
        "ingredients": ["fresh red tomato"]
    },
    "walnut": {
        "density": 0.55,
        "cal_100g": 654.0,
        "protein": 15.2,
        "fat": 65.2,
        "carbs": 13.7,
        "sugars": 2.6,
        "cholesterol": 0.0,
        "dietary_fiber": 6.7,
        "nutrition_density": 86.0,
        "ingredients": ["raw walnut halves"]
    },
    "watermelon": {
        "density": 0.65,
        "cal_100g": 30.0,
        "protein": 0.6,
        "fat": 0.2,
        "carbs": 7.6,
        "sugars": 6.2,
        "cholesterol": 0.0,
        "dietary_fiber": 0.4,
        "nutrition_density": 80.0,
        "ingredients": ["fresh watermelon"]
    },
    "white button mushroom": {
        "density": 0.35,
        "cal_100g": 22.0,
        "protein": 3.1,
        "fat": 0.3,
        "carbs": 3.3,
        "sugars": 2.0,
        "cholesterol": 0.0,
        "dietary_fiber": 1.0,
        "nutrition_density": 90.0,
        "ingredients": ["white button mushroom"]
    },
    "default": {
        "density": 0.5,
        "cal_100g": 100.0,
        "protein": 2.0,
        "fat": 1.0,
        "carbs": 15.0,
        "sugars": 2.0,
        "cholesterol": 0.0,
        "dietary_fiber": 1.0,
        "nutrition_density": 50.0,
        "ingredients": ["assorted ingredients"]
    }
}
